{
  self,
  inputs,
  ...
}: {
  flake.nixosModules.mainpcConfiguration = {pkgs, ...}: {
    imports = [
      # TODO: Add hardware configuration (with nixos-generate-config and --no-filesystems as disko will manage them)

      self.nixosModules.desktop

      self.nixosModules.grub

      inputs.disko.nixosModules.disko
      self.diskoConfigurations.mainpcConfig
    ];

    networking.hostName = "mainpc";

    time.timeZone = "America/New_York";

    system.stateVersion = "26.05"; # TODO: Update from autogenerated config before install
  };
}
